// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Single sidebar, generated from the docs/ folder structure:
 *   - intro.md                          (top-level "Overview" doc)
 *   - tools/       (category, per _category_.json)  — tool-by-tool usage + navigation
 *   - scripting/   (category, per _category_.json)  — the Lua scripting API
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
